const autoprefixer = require("autoprefixer");
const browserSync = require("browser-sync").create();
const cp = require("child_process");
const cssnano = require("cssnano");
const csso = require("postcss-csso");
const del = require("del");
const gulp = require("gulp");
const hugoBin = require("hugo-bin");
const log = require("fancy-log");
const PluginError = require("plugin-error");
const postcss = require("gulp-postcss");
const sass = require("gulp-sass");
const sourcemaps = require("gulp-sourcemaps");
const webpack = require("webpack");
const webpackConfig = require("./webpack.prod");
const webpackDevConfig = require("./webpack.dev");
const purifyCSS = require("gulp-purifycss");
const htmlmin = require("gulp-htmlmin");

const critical = require("critical").stream;

// Compress SASS
gulp.task("sass", () => {
  return gulp
    .src(["./src/sass/styles.scss", "./src/sass/search.scss", "./src/sass/one-signal.scss"])
    .pipe(
      sass({
        outputStyle: "compressed",
      }).on("error", sass.logError)
    )
    .pipe(purifyCSS([
      "./dist/**/*.html",
      "./dist/assets/*.js"
    ]))
    .pipe(postcss([autoprefixer(), cssnano(), csso()]))
    .pipe(sourcemaps.write("."))
    .pipe(gulp.dest("./dist/assets/css"))
    .pipe(browserSync.stream());
});

gulp.task("sass-local", () => {
  return gulp
    .src(["./src/sass/styles.scss", "./src/sass/search.scss"])
    .pipe(
      sass({
        outputStyle: "compressed",
      }).on("error", sass.logError)
    )
    .pipe(gulp.dest("./dist/assets/css"))
    .pipe(browserSync.stream());
});


// Move images
// Leave it to GitHub bot to compress
gulp.task("img", () => {
  return gulp
    .src("./src/img/**/*")
    .pipe(gulp.dest("./dist/assets/img"));
});

// Compile Javascript
gulp.task("js", (done) => {
  const environment = process.env.NODE_ENV;
  log("ENVIRONMENT: " + environment);
  let myConfig = {};
  if (environment === "dev") {
    myConfig = Object.assign({}, webpackDevConfig);
  } else {
    myConfig = Object.assign({}, webpackConfig);
  }
  webpack(myConfig, (err, stats) => {
    if (err) throw new PluginError("webpack", err);
    log(
      "[webpack]",
      stats.toString({
        colors: true,
        progress: true,
      })
    );
    browserSync.reload();
  });
  done();
});

// Minify HTML
gulp.task("html-minify", () => {
  return gulp.src("./dist/**/*.html")
    .pipe(htmlmin({
      collapseBooleanAttributes: true,
      collapseWhitespace: true,
      conservativeCollapse: true,
      decodeEntities: true,
      html5: true,
      includeAutoGeneratedTags: false,
      minifyJS: true,
      removeComments: true,
      removeRedundantAttributes: true
    }))
    .pipe(gulp.dest("./dist"));
});

// Clean up dist
gulp.task("clean", () => {
  return del(["dist"]);
});

// Generate & Inline Critical-path CSS
gulp.task("critical", () => {
  return gulp.src("./dist/*.html")
    .pipe(critical({
      base: "dist/",
      inline: true,
      css: ["./dist/assets/css/styles.css"]
    }))
    .on("error", (err) => {
      log.error(err.message);
    })
    .pipe(gulp.dest("./dist"));
});

// Development server with browsersync
const runServer = (options) => {
  browserSync.init({
    server: {
      baseDir: "./dist"
    }
  });
  gulp.watch("./src/js/**/*.js", gulp.series("js"));
  gulp.watch("./src/sass/**/*.scss", gulp.series("sass-local"));
  gulp.watch("./src/img/**/*", gulp.series("img"));
  gulp.watch("./site/**/*", gulp.series(options));
};

// Run Hugo
const buildSite = (done, options, environment) => {
  const args = options ? hugoArgsDefault.concat(options) : hugoArgsDefault;
  process.env.NODE_ENV = environment;
  return cp.spawn(hugoBin, args, {
    stdio: "inherit"
  }).on("close", (code) => {
    if (code === 0) {
      browserSync.reload();
      done();
    } else {
      browserSync.notify("Hugo build failed :(");
      done("Hugo build failed");
    }
  });
};

// Hugo arguments
const hugoArgsDefault = ["-d", "../dist", "-s", "site", "--verbose"];
const hugoArgsPreview = ["--buildDrafts", "--buildFuture"];

// Development tasks
gulp.task("hugo", (done) => buildSite(done, [], "prod"));
gulp.task("hugo-dev", (done) => buildSite(done, [], "dev"));
gulp.task("hugo-preview", (done) => buildSite(done, hugoArgsPreview, "dev"));

// Server tasks
gulp.task("server", gulp.series("hugo-dev", "sass-local", "img", "js", (done) => {
  runServer("hugo-dev");
  done();
}));

gulp.task("server-prod", gulp.series("hugo", "img", "js", "sass", "html-minify", (done) => {
  runServer("hugo");
  done();
}));

gulp.task("server-preview", gulp.series("hugo-preview", "sass-local", "img", "js", (done) => {
  runServer("hugo-preview");
  done();
}));

// Production tasks
gulp.task("build", gulp.series("clean", "hugo", "img", "js", "sass", "html-minify"));
gulp.task("build-dev", gulp.series("clean", "hugo-dev", "sass-local", "img", "js"));
